SELECT ORDER_ITEMS.quantity FROM ORDER_ITEMS
INNER JOIN PRODUCTS ON ORDER_ITEMS.product_id = PRODUCTS.id
WHERE PRODUCTS.id = 2456;

SELECT name FROM PRODUCTS WHERE stock = 0;

SELECT id FROM ORDERS WHERE order_date > CURRENT_DATE();

SELECT name FROM CUSTOMER WHERE email LIKE '%@gmail.com';
