DROP DATABASE IF EXISTS ecole;

CREATE DATABASE ecole;
USE ecole;

CREATE TABLE enfant (
    numero_ss INT(15) PRIMARY KEY,
    nom VARCHAR(255) NOT NULL,
    prenom VARCHAR(255) NOT NULL
);

CREATE TABLE ecole (
    code_ecole INT AUTO_INCREMENT PRIMARY KEY,
    nom VARCHAR(255) NOT NULL
);

CREATE TABLE commune (
    code_postal INT(6) AUTO_INCREMENT PRIMARY KEY,
    nom VARCHAR(255) NOT NULL
);
